services:
  postgres:
    image: postgres:16-alpine
    container_name: tg_miniapp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tg_miniapp
      POSTGRES_USER: tg_miniapp
      POSTGRES_PASSWORD: tg_miniapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

