version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: tg_apps_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tg_apps
      POSTGRES_USER: tg_apps
      POSTGRES_PASSWORD: tg_apps
    ports:
      - "5433:5432"
    volumes:
      - tg_apps_pgdata:/var/lib/postgresql/data

volumes:
  tg_apps_pgdata:
